---
name: Release vega, data-node, vegawallet and visor binaries

"on":
  push:
    tags:
      - "v*"

jobs:
  release:
    name: "Release for ${{ matrix.os }}-${{ matrix.arch }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        os: [linux, darwin]
    env:
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
      CGO_ENABLED: 0

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go

      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.tag }}

      - name: Build binary
        run: go build -o dist/vega-asistant-${{ matrix.os }}-{{ matrix.arch }} ./main.go

      - name: Bundle binary in archive
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          directory: build
          filename: vega-asistant-${{ matrix.os }}-{{ matrix.arch }}.zip

      - name: Release
        if: ${{ inputs.publish || startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477
        with:
          files: build/*.zip
          name: ${{ inputs.tag || github.ref_name }}
          tag_name: ${{ inputs.tag || github.ref_name }}
          prerelease: true
